title: "me docs"
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"
search_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

favicon_ico: "/img/favicon.ico"


last-modified-at:
​    date-format: '%Y/%m/%d' #2016/03/23.

author:
  name: "MINKY0NG"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sparrowscout"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-last-modified-at
